name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-110-194-247.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: deploy to ec2
        run: |
          ssh ec2-user@ec2-3-110-194-247.ap-south-1.compute.amazonaws.com << 'EOF'
            cd ~/app
            git pull origin master
            docker-compose down
            docker-compose -f docker/docker-compose.yml up --build -d
          EOF
      